version: '3.8'
services:
  app:
    container_name: 1MNoticias-app
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb

  mongodb:
    container_name: 1MNoticias-mongodb
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=1MNoticias
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
